export default [
  // "Category",
  "Child care",
  "Child activities",
  "Child clothes",
  "School tuition",
  "Youth sports",
  "Diapers",
  "Streaming subscription",
  "Internet services subscription",
  "Going out with friends",
  "Movies",
  "Restaurants and dining out",
  "Other hobbies",
  "Cable or satellite TV",
  "Concerts and festivals",
  "Sports tickets",
  "Plays and symphonies",
  "Skiing or snowboarding",
  "Club membership",
  "Lottery tickets",
  "Gambling",
  "Groceries",
  "Haircuts",
  "Dry cleaning",
  "Rent",
  "House payment",
  "Home insurance premium",
  "Property tax",
  "Gas payment",
  "Electric payment",
  "Garbage pickup",
  "Water/sewer",
  "HOA fees",
  "Home Internet",
  "Yard care",
  "Swimming pool maintenance",
  "Maintenance agreements",
  "Home cleaning",
  "Renter's insurance",
  "Health insurance premium",
  "Dental insurance premium",
  "Vision insurance premium",
  "Doctor or specialist visit (inc. copays)",
  "Physical therapy",
  "Chiropractor visits",
  "Other routine medical expenses",
  "Prescription medication",
  "Health Savings Account (HAS) contributions",
  "Glasses",
  "Contact lenses",
  "Charity",
  "Storage fees",
  "Bank overdraft reserve line",
  "Credit card payment",
  "Other debt payment",
  "Boat, motorcycle, or other payment",
  "Student loan payment",
  "Apparel and clothing",
  "Subscriptions",
  "Cell phone bill",
  "Gym, yoga, or trainer fees",
  "Educational tuition",
  "Spa costs",
  "Massage costs",
  "Tanning",
  "Pet insurance premium",
  "Pet boarding",
  "Veterinary fees",
  "Pet grooming",
  "Pet waste disposal",
  "Pet food",
  "Life insurance premium",
  "Other insurance premium",
  "Federal, state, and local income taxes",
  "Investments",
  "Recurring investments (i.e. 401(k) deduction)",
  "Boat, motorcycle, or other insurance",
  "Auto lease payment",
  "Auto loan payment",
  "Auto insurance premium",
  "Gasoline or fuel costs",
  "Public transport fees",
  "Parking expenses",
  "Auto registration (annual)",
  "Vehicle maintenance",
  "Salary",
  "Wages",
  "Bonus",
  "Investment income",
  "Interest income",
  "Rental income",
  "Alimony",
  "Child support",
  "Side gig",
  "Income from business ownership",
  "Social Security or Disability income",
  "SNAP, WIC, or other government assistance"
];
